export const RESET_FILES = 'RESET_FILES'
export const ADD_FILE = 'ADD_FILE'
export const ADD_FILES = 'ADD_FILES'

export const FETCH_FILES = 'FETCH_FILES'

export const ADD_REPOSITORY = 'ADD_REPOSITORY'
export const ADD_REPOSITORIES = 'ADD_REPOSITORIES'
export const RESET_REPOSITORIES = 'RESET_REPOSITORIES'

export const FETCH_REPOSITORIES = 'FETCH_REPOSITORIES'